version: '2.2'

services:
  app:
    build: .
    networks:
      - elastic
      - frontend
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"     
    volumes:
      - data01:/usr/share/elasticsearch/data 
    networks:
      - elastic
  nginx:
    image: nginx:1.21-alpine
    volumes:
      -  ./nginx.conf:/etc/nginx/nginx.conf
      -  ./project/flask-app/templates/:/usr/share/nginx/html
      - ./project/flask-app/static/:/usr/share/nginx/static
    ports:
      - 80:80
    networks:
      - frontend
   




volumes:
  data01:
    driver: local  
networks:
  elastic:
  frontend:

      